INSERT INTO news_entries
    (title, slug, excerpt, content, type, version, status, published_at, created_by, updated_by)
VALUES
    (
        'v0.1.0-alpha1 – Projektstart und Grundgerüst',
        'v0-1-0-alpha1-projektstart-und-grundgeruest',
        'Start des Projekts mit Front Controller, Router und Basis-Views.',
        'Erste Grundlage für Modulon als eigenständiges PHP-Projekt.\n\n- Front Controller in public/index.php\n- mod_rewrite über .htaccess\n- Core-Klassen für Request, Response, Router und Application',
        'release',
        '0.1.0-alpha1',
        'published',
        '2026-04-11 09:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-alpha2 – Datenbank, Benutzer und Rollen',
        'v0-1-0-alpha2-datenbank-benutzer-und-rollen',
        'Schema für Benutzer-, Rollen- und Berechtigungsdaten eingeführt.',
        'Der Datenbank-Unterbau wurde für Authentifizierung und Rechteverwaltung vorbereitet.\n\n- users, roles, permissions, user_role, role_permission\n- PDO-Anbindung und ENV-basierte DB-Konfiguration\n- Seed-Rollen user/admin',
        'update',
        '0.1.0-alpha2',
        'published',
        '2026-04-11 11:30:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-beta1 – Login, Session und Remember-Me',
        'v0-1-0-beta1-login-session-und-remember-me',
        'Auth-Flow mit Session-Lifecycle und persistentem Login umgesetzt.',
        'Das Auth-System wurde von Registrierung bis Logout durchgezogen.\n\n- password_hash/password_verify\n- Idle-Timeout und absolute Session-Laufzeit\n- Remember-Me mit gehashten, rotierenden Tokens',
        'release',
        '0.1.0-beta1',
        'published',
        '2026-04-11 14:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-beta2 – 2FA mit TOTP, WebAuthn und Recovery Codes',
        'v0-1-0-beta2-2fa-totp-webauthn-recovery-codes',
        'Mehrstufige 2FA-Optionen für produktionsnahe Sicherheit ergänzt.',
        'Die Sicherheitsfunktionen wurden deutlich erweitert.\n\n- TOTP inkl. Setup-Verifikation\n- WebAuthn/Passkeys mit mehreren Credentials\n- Recovery Codes, gehasht gespeichert und einmalig nutzbar',
        'release',
        '0.1.0-beta2',
        'published',
        '2026-04-11 17:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-rc1 – Adminbereich und Modulverwaltung',
        'v0-1-0-rc1-adminbereich-und-modulverwaltung',
        'Adminwerkzeuge und dynamische Modulrouten aus der Datenbank eingeführt.',
        'Aus dem Grundsystem wurde ein administrierbares Modulsystem.\n\n- /admin mit Modulverwaltung\n- Zugriffsstufen public/user/admin\n- Aktivierte Module werden zur Laufzeit als Routen geladen',
        'release',
        '0.1.0-rc1',
        'published',
        '2026-04-11 20:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-rc2 – Legacy-Integration und Overlay-Injection',
        'v0-1-0-rc2-legacy-integration-und-overlay-injection',
        'Legacy-Apps wurden als Module anbaubar und zentral steuerbar gemacht.',
        'Der Fokus lag auf Integration bestehender Anwendungen ohne Rewrite.\n\n- Legacy-Dispatcher mit Datei-/Asset-Auslieferung\n- Admin-Entry-Unterstützung pro Modul\n- Serverseitige Overlay-Injection für angemeldete Modulon-User',
        'update',
        '0.1.0-rc2',
        'published',
        '2026-04-12 12:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0-rc3 – UI-System, Dark Mode und Branding',
        'v0-1-0-rc3-ui-system-dark-mode-und-branding',
        'Gemeinsames Layout, konsistente Komponenten und Branding-Assets eingebaut.',
        'Die Oberfläche wurde über alle Kernbereiche vereinheitlicht.\n\n- Zentrales Layout mit Navbar/Footer\n- Light/Dark Theme über CSS-Variablen\n- Modulon-Branding (Icon/Logo) und Overlay-Feinschliff',
        'update',
        '0.1.0-rc3',
        'published',
        '2026-04-14 10:00:00',
        NULL,
        NULL
    ),
    (
        'v0.1.0 – Native News-/Changelog-Modul live',
        'v0-1-0-native-news-changelog-modul-live',
        'Das erste native Nicht-Legacy-Modul ersetzt den News-Platzhalter.',
        'Das News-Modul dient als zentrale Entwicklungsübersicht für Modulon.\n\n- Öffentliche Übersicht und Detailseiten unter /news\n- Admin-CRUD unter /admin/news\n- Struktur für Releases, Updates, Notes und Versionierung',
        'release',
        '0.1.0',
        'published',
        '2026-04-15 09:00:00',
        NULL,
        NULL
    ),
    (
        'v0.3.0 – Dashboard, Mail-Hub und System-Hardening',
        'v0-3-0-dashboard-mail-hub-system-hardening',
        'Großes Funktionsupdate mit Dashboard-Widgets, modernisiertem Mail-Modul, Systemcheck und konsolidierter Benutzer-/Admin-UX.',
        'Seit dem letzten GitHub-Upload wurde Modulon in mehreren Bereichen substanziell erweitert.\n\n- Dashboard als natives Modul mit usergebundenen Widgets (Links, Aufgaben, Notizen), AJAX-Interaktionen, wiederkehrenden Aufgaben inkl. Reaktivierung und konsistentem Formular-UX-Flow.\n- Links-Widget robust gemacht: URL-Analyse, sichere Favicon-Erkennung, lokales Favicon-Handling, Bearbeiten/Löschen und verbesserte Fehlerbehandlung.\n- Profilbereich ausgebaut (Profil/Sicherheit/Einstellungen), inklusive benutzerbezogener Zeitzone als Grundlage für zeitbasierte Features.\n- Admin- und Modularchitektur weiter vereinheitlicht: native Modultypen, transparente Modul-Einstiege, Sortierung/Sichtbarkeit und konsistentere Navigation.\n- Neues natives Modul Systeminfo mit strukturierten Karten, Header-Feinschliff, Serverzeit/Zeitzone und erweitertem Systemcheck.\n- Mail-Modul als Multi-Account-Hub ausgebaut: Kontoverwaltung, Ordner/Favoriten, Nachrichtenliste mit getrennter Sortierung/Gruppierung, sichere Nachrichtendarstellung, Compose/Reply und SMTP-Versand.\n- Mail-Transport modernisiert: `webklex/php-imap` + `symfony/mailer`, ohne ext-imap, mit klaren Voraussetzungen und degradiertem Verhalten bei fehlenden Runtime-Requirements.\n- Zentrales Error-/Debug-Handling auf Basis von APP_ENV/APP_DEBUG ergänzt, inklusive Logging und sauberer Development-/Production-Trennung.\n- README, Architekturdoku und Projekt-Memory entlang der neuen Architekturstände aktualisiert.',
        'release',
        '0.3.0',
        'published',
        '2026-04-20 18:00:00',
        NULL,
        NULL
    ),
    (
        'v0.3.1 – Mail-Viewer stabilisiert, Auth-Debugging und lokales E2E-Setup',
        'v0-3-1-mail-viewer-stabilisiert-auth-debugging-e2e-setup',
        'Fokus-Update auf Mail-UX, robustes HTML-Rendering, Login-Diagnostik und reproduzierbare Browser-E2E-Tests.',
        'Dieses Update schließt die letzten großen Mail-UX-/Rendering-Lücken und stärkt die Entwicklungsqualität.\n\n- Mail-Arbeitsbereich stabilisiert: konsistente Split-View mit Vorschau-Toggle, persistenter Pane-Größe und robustem Verhalten beim Nachrichtenwechsel.\n- HTML-Mail-Rendering gehärtet: iframe-basierte, isolierte Darstellung mit deutlich originalgetreuerem Layout bei weiterhin strikter Sanitization und kontrollierter Bildfreigabe.\n- Bilderfreigabe im Vorschau-Kontext korrigiert: kein Navigieren auf nackte `partial=1`-Ansichten mehr, sondern Reload im bestehenden Preview-Flow.\n- Mail-Listenperformance und Bedienfluss weiter verbessert (Header-/Index-Cache, Nachladen, Absenderansicht-Flow, konsistente Navigation Arbeitsbereich/Verfassen/Konten & Ordner).\n- Login-Debugging ausgebaut: fehlgeschlagene Logins werden intern strukturiert protokolliert (ohne Passwort-Leak), inklusive klarer Fehlklassifikation zur schnelleren Ursachenanalyse.\n- Lokales Browser-E2E-Testsetup ergänzt: Python + pytest + Playwright (Chromium), inklusive Smoke-Tests für Startseite, Login und Mail-Grundfluss.\n- System-/Runtime-Verhalten präzisiert: HEAD-Requests sauber auf GET-Routen aufgelöst, ohne Response-Body.\n- Dokumentation und Projekt-Memory entlang des neuen Stands aktualisiert.',
        'release',
        '0.3.1',
        'published',
        '2026-04-22 11:30:00',
        NULL,
        NULL
    ),
    (
        'v0.4.0 – Native Banking-App und modulare Laufzeit',
        'v0-4-0-native-banking-app-und-modulare-laufzeit',
        'Großes Architektur- und Funktionsupdate mit nativem Banking-Modul, Modul-Auto-Discovery, modularer Admin-/User-Navigation und weiteren Dashboard-Verbesserungen.',
        'Dieses Release bringt Modulon deutlich näher an das Ziel einer wirklich modularen Plattform.\n\n- Native Modul-Laufzeit eingeführt: Fachmodule können Routen, Untermenüs, Adminbereiche, User-Navigation und Binding-Metadaten selbst registrieren.\n- Modul-Auto-Discovery ergänzt: neue Modulordner werden in der Modulverwaltung erkannt und deaktiviert angelegt, während die manuelle Registrierung als Fallback erhalten bleibt.\n- News, Dashboard, Mail, Profil, Systeminfo und Banking laufen über eigene Modulklassen statt über zentrale Core-Sonderverdrahtung.\n- Native Banking-App stark ausgebaut: Dashboard, Umsatzliste, Monatsübersicht, wiederkehrende Regeln, Fälligkeitsstatus, Sparkassen-CSV-Import, Duplikaterkennung und kontrolliertes Löschen eigener Duplikate.\n- Banking-Legacy-Fallback bleibt parallel unter `/banking-old` erreichbar, während die native UI ausschließlich user_id-gescoped auf Modulon-Tabellen arbeitet.\n- Banking-Import robuster gemacht: optionale Kategorie-Spalte, bessere Erkennung vorhandener/vorgemerkter Buchungen und Batch-/Rollback-Grundlage.\n- Dashboard verfeinert: Profilabhängige Settings-Links, User-Dropdown aus Modul-Navigation, Auto-Refresh-Pause bei Dialogen und abgesicherte lange Linktitel.\n- Adminbereich modularisiert: Admin-Dropdown, modulbasierte Admin-Navigation und bereinigte Modulverwaltung.\n- Viele UI-Details in Banking, Dashboard und Profil korrigiert, inklusive Zahlenformatierung, Tooltips, Sticky-Tabellenkopf, Statusfarben und klarerer Hilfetexte.\n- README, technische Architektur und Projekt-Memory wurden an den neuen Modulstand angepasst.',
        'release',
        '0.4.0',
        'published',
        '2026-04-27 18:00:00',
        NULL,
        NULL
    ),
    (
        'v0.5.0 alpha – Erster öffentlicher ModulNest-Release',
        'v0-5-0-alpha-erster-oeffentlicher-modulnest-release',
        'ModulNest wurde erstmals als öffentliches GitHub-Projekt mit Bootstrap-Installer, Source-/Bundled-Paketen und MIT-Lizenz veröffentlicht.',
        'Mit v0.5.0 wurde aus dem privaten Arbeitsprojekt Modulon der erste öffentliche ModulNest-Alpha-Stand.\n\n- Öffentlicher Produktname auf ModulNest festgelegt; Modulon bleibt der interne Core-/Arbeitsname.\n- Bereinigter Public-Export nach `/srv/http/modulnest` und Veröffentlichung im GitHub-Repo `ChobitsChii/ModulNest`.\n- Source- und Bundled-ZIP-Pakete als Release-Assets eingeführt: Source ohne `vendor/` für Composer-Installationen, Bundled mit `vendor/` für normale Webspaces ohne Composer.\n- `build/update/stable.json` als maschinenlesbare Release-Metadaten mit Paket-URLs und SHA256-Prüfsummen ergänzt.\n- Bootstrap-Installer `install.php` aufgebaut: Systemcheck, Paketwahl, Datenbanktest, erstes Admin-Konto, Modul-Auswahl und Installationslog.\n- Download und Installation werden per SHA256 geprüft und ZIP-Slip-sicher entpackt.\n- Installer erzeugt lokale Konfiguration, führt das Schema aus, legt den ersten Admin an und versucht sich nach erfolgreicher Installation selbst zu löschen.\n- README und öffentliche Dokumentation wurden auf ModulNest ausgerichtet und stark aufgeräumt.\n- MIT-Lizenz ergänzt.',
        'release',
        '0.5.0',
        'published',
        '2026-05-08 14:16:40',
        NULL,
        NULL
    ),
    (
        'v0.5.1 alpha – PHP-FPM-/FastCGI-Hotfix',
        'v0-5-1-alpha-php-fpm-fastcgi-hotfix',
        'Hotfix für Apache/PHP-FPM-Setups: mod_php-spezifische .htaccess-Direktiven wurden entfernt.',
        'Dieses Patch-Release behebt einen HTTP-500-Fehler auf modernen PHP-FPM-/FastCGI-/CGI-Setups.\n\n- `php_value`- und `php_flag`-Direktiven aus `public/.htaccess` entfernt.\n- `.htaccess` enthält damit nur noch Rewrite-/Routing-Regeln, die auch ohne mod_php funktionieren.\n- `public/.user.ini.example` als Vorlage für optionale PHP-Limits ergänzt.\n- Dokumentation zu PHP-FPM/FastCGI, Hosting-Panels, `php.ini`, PHP-FPM-Pool-Konfiguration und `.user.ini` aktualisiert.\n- Bestehende Installationen müssen für diesen Fehler nicht neu installiert werden; das Ersetzen von `public/.htaccess` reicht.',
        'release',
        '0.5.1',
        'published',
        '2026-05-08 17:11:06',
        NULL,
        NULL
    ),
    (
        'v0.6.0 alpha – Admin-Updates-Modul',
        'v0-6-0-alpha-admin-updates-modul',
        'ModulNest erhält erstmals ein Admin-Modul, um offizielle Release-ZIPs aus stable.json zu prüfen, vorzubereiten und zu installieren.',
        'v0.6.0 bringt die erste robuste Update-Funktion für bestehende ModulNest-Installationen.\n\n- Neues Admin-Updates-Modul unter `/admin/updates`.\n- Updateprüfung über die offizielle `stable.json`.\n- Für normale Webinstallationen wird das Bundled-ZIP bevorzugt, damit kein Composer auf dem Zielsystem nötig ist.\n- Release-ZIP wird heruntergeladen, per SHA256 geprüft und ZIP-Slip-sicher entpackt.\n- Update-Vorbereitung nutzt ein Staging-Verzeichnis unter `storage/updates`.\n- Vor dem Überschreiben wird ein Datei-Backup unter `storage/backups/updates` erstellt.\n- Einfacher Wartungsmodus über `storage/maintenance.flag` vorbereitet.\n- Schutzliste verhindert das Überschreiben oder Kopieren sensibler Bereiche wie `.env`, `storage`, `.git`, `.local`, `install.php` und lokaler Runtime-Daten.\n- `public/.htaccess`, App-Dateien, Assets, Dokumentation, Composer-Dateien, Paketmetadaten und `vendor/` aus Bundled-Paketen können aktualisiert werden.\n- v1 führt keine automatische riskante Datenbankmigration aus; mögliche DB-Änderungen werden als Hinweis behandelt.\n- Für bestehende 0.5.x-Installationen muss das Updates-Modul einmalig manuell eingespielt und aktiviert werden.',
        'release',
        '0.6.0',
        'published',
        '2026-05-08 19:05:48',
        NULL,
        NULL
    ),
    (
        'v0.6.1 alpha – Versionsanzeige und Update-UX korrigiert',
        'v0-6-1-alpha-versionsanzeige-und-update-ux-korrigiert',
        'Patch-Release für die Versionslogik nach Updates und mehrere UI-Korrekturen im Admin-Updates-Modul.',
        'v0.6.1 korrigiert die wichtigste Nacharbeit am neuen Updates-Modul.\n\n- Die angezeigte App-Version kommt jetzt zuverlässig aus `app/Config/version.php`.\n- Alte `.env`-Einträge wie `APP_VERSION` oder `APP_CHANNEL` überschreiben die Code-/Release-Version nicht mehr.\n- Neue Installationen schreiben `APP_VERSION` und `APP_CHANNEL` nicht mehr in `.env`, damit Datei-Updates die sichtbare Version nicht blockieren.\n- Update-State wird nach erfolgreichem Update normalisiert, sodass ein bereits installiertes Update nicht weiter als verfügbar angezeigt wird.\n- Updates-Seite zeigt Datums- und Zeitangaben deutsch formatiert und mit der Zeitzone des aktuellen Users.\n- Externe Links im Updates-Modul öffnen in einem neuen Tab und sind mit Icon markiert.\n- Versions-/Channel-Anzeige ist im Dark Theme besser lesbar.\n- Live-Update von 0.6.0 auf 0.6.1 funktioniert über das Updates-Modul ohne manuellen Dateiersatz, sofern das 0.6.0-Updates-Modul bereits installiert und aktiv ist.',
        'release',
        '0.6.1',
        'published',
        '2026-05-08 23:11:45',
        NULL,
        NULL
    )
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    excerpt = VALUES(excerpt),
    content = VALUES(content),
    type = VALUES(type),
    version = VALUES(version),
    status = VALUES(status),
    published_at = VALUES(published_at),
    updated_by = VALUES(updated_by),
    updated_at = CURRENT_TIMESTAMP;
