<?php
declare(strict_types=1);
namespace ModulNest\Wiki;
final class WikiRepository {
 public function __construct(private readonly \PDO $pdo) {}
 public function source(): ?array { $row=$this->pdo->query('SELECT * FROM wiki_sources ORDER BY id ASC LIMIT 1')->fetch(); return is_array($row)?$row:null; }
 public function saveSource(array $data): int { $data += ['source_type'=>'github']; $source=$this->source(); if($source===null){$s=$this->pdo->prepare('INSERT INTO wiki_sources(source_type,repository_owner,repository_name,ref_name,docs_root,enabled) VALUES(:source_type,:owner,:repo,:ref,:root,:enabled)');$s->execute($data);return (int)$this->pdo->lastInsertId();} $data['id']=$source['id'];$s=$this->pdo->prepare('UPDATE wiki_sources SET source_type=:source_type,repository_owner=:owner,repository_name=:repo,ref_name=:ref,docs_root=:root,enabled=:enabled WHERE id=:id');$s->execute($data);return (int)$source['id']; }
 public function page(string $route): ?array { $s=$this->pdo->prepare('SELECT * FROM wiki_pages WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1) AND route_path=:route AND hidden=0 LIMIT 1');$s->execute(['route'=>$route]);$r=$s->fetch();return is_array($r)?$r:null; }
 public function rootPage(): ?array { $sql="SELECT * FROM wiki_pages WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1) AND hidden=0 ORDER BY CASE relative_path WHEN 'README.md' THEN 1 WHEN 'index.md' THEN 2 WHEN 'README.markdown' THEN 3 WHEN 'index.markdown' THEN 4 ELSE 5 END, sort_order ASC, route_path ASC LIMIT 1";$r=$this->pdo->query($sql)->fetch();return is_array($r)?$r:null; }
 public function pages(): array { $r=$this->pdo->query('SELECT * FROM wiki_pages WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1) AND hidden=0 ORDER BY route_path ASC, sort_order ASC')->fetchAll();return is_array($r)?$r:[]; }
 public function pageCount(): int { return (int)$this->pdo->query('SELECT COUNT(*) FROM wiki_pages WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1)')->fetchColumn(); }
 public function visiblePageCount(): int { return (int)$this->pdo->query('SELECT COUNT(*) FROM wiki_pages WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1) AND hidden=0')->fetchColumn(); }
 public function assetCount(): int { return (int)$this->pdo->query('SELECT COUNT(*) FROM wiki_assets WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1)')->fetchColumn(); }
 public function asset(string $path): ?array { $s=$this->pdo->prepare('SELECT * FROM wiki_assets WHERE source_id=(SELECT id FROM wiki_sources ORDER BY id LIMIT 1) AND relative_path=:path LIMIT 1');$s->execute(['path'=>$path]);$r=$s->fetch();return is_array($r)?$r:null; }
 public function replaceIndex(int $sourceId,array $pages,array $assets,string $sha,array $activeSource=[]): array { $old=$this->pdo->prepare('SELECT relative_path,content_hash FROM wiki_pages WHERE source_id=:id');$old->execute(['id'=>$sourceId]);$before=[];foreach($old->fetchAll()?:[] as $r)$before[$r['relative_path']]=$r['content_hash'];$added=$changed=0;foreach($pages as $p){if(!isset($before[$p['relative_path']]))$added++;elseif($before[$p['relative_path']]!==$p['content_hash'])$changed++;}$paths=array_column($pages,'relative_path');$deleted=count(array_diff(array_keys($before),$paths));
  // Remove vanished paths first (a replacement README/index may use the same route),
  // then preserve IDs for all genuinely unchanged pages.
  if($paths===[])$this->pdo->prepare('DELETE FROM wiki_pages WHERE source_id=:id')->execute(['id'=>$sourceId]);else{$marks=implode(',',array_fill(0,count($paths),'?'));$d=$this->pdo->prepare("DELETE FROM wiki_pages WHERE source_id=? AND relative_path NOT IN ({$marks})");$d->execute(array_merge([$sourceId],$paths));}
  $p=$this->pdo->prepare('INSERT INTO wiki_pages(source_id,relative_path,route_path,title,content_hash,sort_order,hidden,source_mtime) VALUES(:source_id,:relative_path,:route_path,:title,:content_hash,:sort_order,:hidden,:source_mtime) ON DUPLICATE KEY UPDATE route_path=VALUES(route_path),title=VALUES(title),content_hash=VALUES(content_hash),sort_order=VALUES(sort_order),hidden=VALUES(hidden),source_mtime=VALUES(source_mtime)');foreach($pages as $row)$p->execute($row+['source_id'=>$sourceId]);
  $this->pdo->prepare('DELETE FROM wiki_assets WHERE source_id=:id')->execute(['id'=>$sourceId]);$a=$this->pdo->prepare('INSERT INTO wiki_assets(source_id,relative_path,content_hash,mime_type) VALUES(:source_id,:relative_path,:content_hash,:mime_type)');foreach($assets as $row)$a->execute($row+['source_id'=>$sourceId]);$u=$this->pdo->prepare("UPDATE wiki_sources SET last_commit_sha=:sha,last_sync_status='success',last_sync_at=CURRENT_TIMESTAMP,last_error_code=NULL,last_error_message_safe=NULL,active_source_type=:active_type,active_repository_owner=:active_owner,active_repository_name=:active_repository,active_ref_name=:active_ref,active_docs_root=:active_root WHERE id=:id");$u->execute(['sha'=>$sha,'id'=>$sourceId,'active_type'=>(string)($activeSource['source_type']??'github'),'active_owner'=>(string)($activeSource['repository_owner']??''),'active_repository'=>(string)($activeSource['repository_name']??''),'active_ref'=>(string)($activeSource['ref_name']??''),'active_root'=>(string)($activeSource['docs_root']??'')]);return compact('added','changed','deleted'); }
 public function failure(int $id,string $code,string $message): void { $s=$this->pdo->prepare("UPDATE wiki_sources SET last_sync_status='failed',last_error_code=:code,last_error_message_safe=:message WHERE id=:id");$s->execute(['id'=>$id,'code'=>$code,'message'=>mb_substr($message,0,255)]); }
 public function run(int $sourceId,string $status,?string $sha,array $counts=[],?string $error=null): void { $s=$this->pdo->prepare('INSERT INTO wiki_sync_runs(source_id,finished_at,commit_sha,status,added_count,changed_count,deleted_count,safe_error_code) VALUES(:id,CURRENT_TIMESTAMP,:sha,:status,:added,:changed,:deleted,:error)');$s->execute(['id'=>$sourceId,'sha'=>$sha,'status'=>$status,'added'=>$counts['added']??0,'changed'=>$counts['changed']??0,'deleted'=>$counts['deleted']??0,'error'=>$error]); }
}
